name: QGIS-helpers
channels:
  - conda-forge
dependencies:
  - python=3.7*
  - pyproj
  - geopandas
  - psycopg2
  - geoalchemy2
  - qgis
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
      - git+https://github.com/aaronfraint/postGIS-tools.git
